### ISSUE TITLE
Tracing does not work in the dylib

### ISSUE THREAD

**Issue by SamRodri** [JakkuSakura/tracing-shared-rs#2]
In the #1 pull request code `tracing::info!` does not print.

**Comment by JakkuSakura** [comment]
Thanks for reporting. I'll investigate the reason

**Comment by JakkuSakura** [comment]
Figured it out. Dispatch is doing sneaky things in its new
```rust
impl<S> From<S> for Dispatch
where
    S: Subscriber + Send + Sync + 'static,
{
    #[inline]
    fn from(subscriber: S) -> Self {
        Dispatch::new(subscriber)
    }
}
impl Dispatch {
    pub fn new<S>(subscriber: S) -> Self
    where
        S: Subscriber + Send + Sync + 'static,
    {
        let me = Dispatch {
            subscriber: Kind::Scoped(Arc::new(subscriber)),
        };
        callsite::register_dispatch(&me);
        me
    }
}
```

**Comment by JakkuSakura** [comment]
It's worked around now. closing
<img width="371" alt="image" src="https://github.com/JakkuSakura/tracing-shared-rs/assets/33482468/e7681376-7130-4441-9934-5839b8fac827">

basically it's to set a FakeSubscriber and convert it into Dispatch
